x-airflow-common: &airflow-common
  image: apache/airflow:2.8.1
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__FERNET_KEY: ""
    PYTHONPATH: /opt/airflow
    API_URL: http://api:8000/v1/market-data
  volumes:
    - ./dags:/opt/airflow/dags
    - ./etl:/opt/airflow/etl
    - ./logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    ports:
      - "8000:8000"

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: >
      -c "
      pip install requests psycopg2-binary &&
      airflow db migrate &&
      airflow users create \
        --username airflow \
        --password airflow \
        --firstname Airflow \
        --lastname Admin \
        --role Admin \
        --email airflow@example.com || true
      "

  airflow-webserver:
    <<: *airflow-common
    command: >
      bash -c "pip install requests psycopg2-binary && airflow webserver"
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      api:
        condition: service_started

  airflow-scheduler:
    <<: *airflow-common
    command: >
      bash -c "pip install requests psycopg2-binary && airflow scheduler"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      api:
        condition: service_started

volumes:
  postgres-db-volume: